version: "2"

services:
    nginx:
        image: nginx
        ports:
            - "888:80"
        volumes:
            - ./html:/var/www/test/
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        command: /bin/bash -c "exec nginx -g 'daemon off;'"
        links:
            - php

    php:
        build: ./php
        volumes:
            - ./html:/var/www/test/
        links:
            - mysql

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - /var/lib/test_mysql/:/var/lib/mysql/
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: test

    adminer:
        image: adminer
        ports:
            - 8888:8080
